default: &default
  adapter:postgresql

development:
  adapter: sqlite3
  database: db/master.sqlite3

  test:
  <<: *default
   database:db/test.sqlite3

production:
  <<:*default
  adapter: postgresql
  database: d51kiotts59269
  username: jflqlhhozfgxud
  host: ec2-107-23-76-12.compute-1.amazonaws.com
  password:34f9b9b43be56dfbf9c2d5a26c093c031b0a8be6e667a15ca00badb4ca477b80